on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    # TODO: Uncomment `cargo fmt` test once cargo fmt is run
    #- name: cargo fmt
    #  uses: actions-rs/cargo@v1
    #  with:
    #    command: fmt
    #    args: --all -- --check

    # TODO: Uncomment `cargo clippy` once all clippy lints are addressed
    #- name: cargo clippy
    #  uses: actions-rs/cargo@v1
    #  with:
    #    command: clippy
    #    args: --workspace --all-targets -- --deny=warnings

    # TODO: Uncomment `cargo test` if/when the tests can be run without the need for
    #       an API key environment variable
    #- name: cargo test
    #  uses: actions-rs/cargo@v1
    #  with:
    #    command: test
    #    args: --verbose

    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build

